### ISSUE TITLE
Building docker image failed: "/spark/storybook-static" not found

### ISSUE THREAD

**Issue by mbuse** [CoreMedia/coremedia-headless-client-react#15]
**Describe the bug**

I am trying to build the Spark-App in version 2204.0.0 on Windows WSL2 (Ubuntu) using the following commands

    pnpm install
    pnpm run build
    
    DOCKER_BUILDKIT=1 docker build -t "coremedia/spark-client:latest" ./apps

The “pnpm install” and “pmpn build” works fine, but when I am trying to create the docker images (vor spark app and stitching) I receive the following error:

    [+] Building 1.5s (7/9)
    => [internal] load build definition from Dockerfile                                                                                                                0.0s
    => => transferring dockerfile: 38B                                                                                                                                 0.0s
    => [internal] load .dockerignore                                                                                                                                   0.0s
    => => transferring context: 2B                                                                                                                                     0.0s
    => [internal] load metadata for docker.io/library/nginx:1.21-alpine                                                                                                1.2s
    => CANCELED [1/5] FROM docker.io/library/nginx:1.21- alpine@sha256:a74534e76ee1121d418fa7394ca930eb67440deda413848bc67c68138535b989                                 0.2s
    => => resolve docker.io/library/nginx:1.21-alpine@sha256:a74534e76ee1121d418fa7394ca930eb67440deda413848bc67c68138535b989                                          0.0s
    => => sha256:e00351ea626cd356c69e58d33181233b47a904d3b6ee508948d6cc221d7b9cfa 0B / 603B                                                                            0.2s
    => => sha256:a285f0f83eed13cf71ccb560c31dd31b5eb7be0cadb4f43319d6de59aa4e3c70 0B / 7.34MB                                                                          0.2s
    => => sha256:a74534e76ee1121d418fa7394ca930eb67440deda413848bc67c68138535b989 1.65kB / 1.65kB                                                                      0.0s
    => => sha256:529db430e042ecef071f2e88267cee6da18f8ab44d66a0c44348886fdc2e60fc 1.57kB / 1.57kB                                                                      0.0s
    => => sha256:b1c3acb28882519cf6d3a4d7fe2b21d0ae20bde9cfd2c08a7de057f8cfccff15 8.75kB / 8.75kB                                                                      0.0s
    => => sha256:df9b9388f04ad6279a7410b85cedfdcb2208c0a003da7ab5613af71079148139 0B / 2.81MB                                                                          0.2s
    => [internal] load build context                                                                                                                                   0.2s
    => => transferring context: 13.73MB                                                                                                                                0.2s
    => CACHED [2/5] COPY spark/build /usr/share/nginx/html                                                                                                             0.0s
    => ERROR [3/5] COPY spark/storybook-static /usr/share/nginx/html/storybook        0.0s
    ------
    > [3/5] COPY spark/storybook-static /usr/share/nginx/html/storybook:
    ------
    failed to compute cache key: "/spark/storybook-static" not found: not found

I had a look at the Dockerfile at [/apps/Dockerfile](https://github.com/CoreMedia/coremedia-headless-client-react/blob/main/apps/Dockerfile), and it contains the line

    COPY spark/storybook-static /usr/share/nginx/html/storybook

, but the folder spark/storybook-static is not part of the workspace.

**To Reproduce**
1. Check out v2204.0.0 and build the docker image 
2. See error

**Expected behavior**
No build error.

**Desktop (please complete the following information):**
 - OS: Windows 10, WSL2 (Ubuntu)

**Comment by pitgrap** [comment]
The Dockerfile includes storybook, see https://github.com/CoreMedia/coremedia-headless-client-react/blob/main/apps/Dockerfile#L4

You have 2 options to quickfix this:
1) With Storybook; Run `pnpm build-storybook` inside `apps/spark`. This will generate the storybook-static folder. (https://github.com/CoreMedia/coremedia-headless-client-react/blob/main/apps/spark/package.json#L18)
2) Without Storybook. If you do not need storybook, just remove the line in the Dockerfile.

I will check if I can optimize the dockerfile, so it will work with both use cases.
