### ISSUE TITLE
Fails with coremedia.training

### ISSUE THREAD

**Issue by OlegKunitsyn** [CoreMedia/coremedia-headless-client-react#29]
**Describe the bug**
The client does not work with https://headless-server-preview.cm95.coremedia.training/graphql

**To Reproduce**
1. Create '.env' file
2. Put 'COREMEDIA_ENDPOINT=https://headless-server-preview.cm95.coremedia.training/graphql.'
3. 'pnpm build'
4. 'pnpm start'
5. Go 'http://localhost:5173/'
6. See error '400 - Apollo Client Error'

**Expected behavior**
The application should work as expected.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser FireFox

**Comment by pitgrap** [comment]
Hi, sorry for the late answer. 

- Where did you create the ".env" file? It has to be done in "servers/stitching/". 
- Did both server (commerce mocking + stitching) start successfully?
- Which CMCC version are https://headless-server-preview.cm95.coremedia.training based on? Did you start the same headless client? New releases are mostly not backward-compatible.

**Comment by OlegKunitsyn** [comment]
No hurry. 
- servers/stitching/.env
`COREMEDIA_ENDPOINT=https://headless-server-preview.cm95.coremedia.training/graphql`
- I think so: 
```
pnpm start

> @coremedia-labs/headless-client-workspace@2307.0.0 start /home/olegs/projects/ocm
> concurrently "pnpm --filter @coremedia-labs/headless-server-mocking start" "pnpm --filter @coremedia-labs/headless-server-stitching start" "pnpm --filter @coremedia-labs/spark start"

[0] 
[0] > @coremedia-labs/headless-server-mocking@1.0.0 start /home/olegs/projects/ocm/servers/mocking
[0] > node ./bin/smoke -o all -d 10 mocks
[0] 
[2] 
[2] > @coremedia-labs/spark@1.0.0 start /home/olegs/projects/ocm/apps/spark
[2] > vite
[2] 
[1] 
[1] > @coremedia-labs/headless-server-stitching@1.0.0 start /home/olegs/projects/ocm/servers/stitching
[1] > nodemon --watch "src/**" --ext "ts" --exec "ts-node ./src/index.ts"
[1] 
[1] [nodemon] 3.0.1
[1] [nodemon] to restart at any time, enter `rs`
[1] [nodemon] watching path(s): src/**
[1] [nodemon] watching extensions: ts
[1] [nodemon] starting `ts-node ./src/index.ts`
[0] 2023-09-27 13:42:09 [INFO]  Mocking server started on: http://localhost:5000
[2] 
[2]   VITE v4.4.7  ready in 362 ms
[2] 
[2]   ➜  Local:   http://localhost:5173/
[2]   ➜  Network: use --host to expose
[1] 2023-09-27 13:42:11 [INFO]  Fetching schemas from GraphQL endpoints
[1] 2023-09-27 13:42:11 [INFO]  Loading schema from https://headless-server-preview.cm95.coremedia.training/graphql (Headless Server).
[1] 2023-09-27 13:42:14 [INFO]  Successfully loaded schema from coreMediaHeadlessServerEndpoint.
[1] 2023-09-27 13:42:14 [INFO]  Loading schema from http://localhost:5000/graphql (Headless Commerce Server).
[1] 2023-09-27 13:42:14 [INFO]  Successfully loaded schema from commerceCatalogEndpoint.
[1] 2023-09-27 13:42:14 [INFO]  Campaign Service not configured.
[1] 2023-09-27 13:42:15 [INFO]  Stitching server started on: http://localhost:4000/graphql
```
- The version CoreMedia uses for trainings. Shall I start additional clients/servers? I simply following the README...

**Comment by pitgrap** [comment]
> 2023-09-27 13:42:09 [INFO]  Mocking server started on: http://localhost:5000
> 2023-09-27 13:42:15 [INFO]  Stitching server started on: http://localhost:4000/graphql

That looks good. Then we have to look into the browser developer tools. 
- Any errors, warnings in the console log? 
- In the network tab, look for the POST graphql queries and look at the response json. What's in the error response?
- You can also add a .env in "apps/spark" to set "VITE_LOGLEVEL=debug", see https://github.com/CoreMedia/coremedia-headless-client-react/blob/main/apps/spark/.env.example#L26

**Comment by OlegKunitsyn** [comment]
HTTP 400 on POST http://localhost:4000/graphql
`{"operationName":"Site","variables":{"rootSegment":"calista"},"query":"query Site($rootSegment: String!) {\n  content {\n    site(rootSegment: $rootSegment) {\n      id\n      locale\n      __typename\n    }\n    pageByPath(path: $rootSegment) {\n      grid {\n        id\n        placements(names: [\"header\", \"footer\", \"footer-navigation\"]) {\n          ...PageGridPlacement\n          __typename\n        }\n        __typename\n      }\n      localizedVariants {\n        ...LocalizedVariant\n        __typename\n      }\n      ...CMTeasableForNavigation\n      ... on CMExternalChannel {\n        id\n        categoryRef {\n          id\n          category {\n            children {\n              ...Category\n              children {\n                ...Category\n                __typename\n              }\n              __typename\n            }\n            __typename\n          }\n          __typename\n        }\n        __typename\n      }\n      children {\n        ...CMTeasableForNavigation\n        ...CMExternalChannelForNavigation\n        ...CMCollectionForNavigation\n        ...CMProductForNavigation\n        ...CMExternalLinkForNavigation\n        ... on CMCollection {\n          items {\n            ...CMTeasableForNavigation\n            ...CMExternalChannelForNavigation\n            ...CMProductForNavigation\n            ...CMExternalLinkForNavigation\n            ...ProductRef\n            ...CMExternalProduct\n            ... on CMCollection {\n              items {\n                ...CMTeasableForNavigation\n                ...CMExternalChannelForNavigation\n                ...CMProductForNavigation\n                ...CMExternalLinkForNavigation\n                ...ProductRef\n                ...CMExternalProduct\n                __typename\n              }\n              __typename\n            }\n            __typename\n          }\n          __typename\n        }\n        ... on CMExternalChannel {\n          id\n          categoryRef {\n            id\n            category {\n              children {\n                ...Category\n                children {\n                  ...Category\n                  __typename\n                }\n                __typename\n              }\n              __typename\n            }\n            __typename\n          }\n          __typename\n        }\n        ... on CMNavigation {\n          children {\n            ...CMTeasableForNavigation\n            ...CMExternalChannelForNavigation\n            ...CMCollectionForNavigation\n            ...CMProductForNavigation\n            ...CMExternalLinkForNavigation\n            ... on CMNavigation {\n              children {\n                ...CMTeasableForNavigation\n                ...CMExternalChannelForNavigation\n                ...CMCollectionForNavigation\n                ...CMProductForNavigation\n                ...CMExternalLinkForNavigation\n                __typename\n              }\n              __typename\n            }\n            __typename\n          }\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment PageGridPlacement on PageGridPlacement {\n  id\n  name\n  colspan\n  viewtype\n  items {\n    id\n    ...CMTeasable\n    ...CMCollection\n    ...CMVideo\n    ...ShoppableVideo\n    ...CMImageMap\n    ...CMProductTeaser\n    ...CMExternalChannel\n    ...CMSelectionRules\n    ...CMProduct\n    ...CMExternalLink\n    ...CMHTML\n    ...CMPlaceholder\n    ...CMExternalProduct\n    ...CMDownload\n    ... on CMNavigation {\n      children {\n        ...CMTeasable\n        ...CMNavigation\n        ...CMCollection\n        ...CMProduct\n        ...CMExternalLink\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  __typename\n}\n\nfragment CMTeasable on CMTeasable {\n  ...CMLinkable\n  picture {\n    ...CMPicture\n    __typename\n  }\n  media {\n    ...CMPicture\n    ...CMVideo\n    __typename\n  }\n  teaserTitle\n  teaserText {\n    text\n    plaintext: text(view: \"plainFirstParagraph\")\n    __typename\n  }\n  teaserOverlaySettings {\n    ... on TeaserOverlaySettings {\n      style\n      enabled\n      positionX\n      positionY\n      width\n      __typename\n    }\n    __typename\n  }\n  authors {\n    ...CMPerson\n    __typename\n  }\n  extDisplayedDate\n  modificationDate\n  teaserTargets {\n    ...TeaserTarget\n    __typename\n  }\n  subjectTaxonomy {\n    ...CMTaxonomy\n    __typename\n  }\n  __typename\n}\n\nfragment CMLinkable on CMLinkable {\n  id\n  uuid\n  title\n  segment\n  navigationPath {\n    segment\n    id\n    title\n    __typename\n  }\n  __typename\n}\n\nfragment CMPicture on CMPicture {\n  id\n  title\n  data {\n    uri\n    __typename\n  }\n  alt\n  uriTemplate\n  __typename\n}\n\nfragment CMVideo on CMVideo {\n  id\n  title\n  data {\n    uri\n    __typename\n  }\n  dataUrl\n  settings(paths: \"playerSettings\")\n  __typename\n}\n\nfragment CMPerson on CMPerson {\n  ...CMLinkable\n  displayName\n  teaserText {\n    text\n    plaintext: text(view: \"plainFirstParagraph\")\n    __typename\n  }\n  firstName\n  lastName\n  picture {\n    ...CMPicture\n    __typename\n  }\n  __typename\n}\n\nfragment TeaserTarget on ExtendedTeaserTarget {\n  target {\n    ...CMLinkable\n    ... on CMExternalLink {\n      url\n      openInNewTab\n      __typename\n    }\n    ... on CMDownload {\n      data {\n        uri\n        __typename\n      }\n      __typename\n    }\n    ... on CMExternalChannel {\n      id\n      categoryRef {\n        id\n        category {\n          ...CategoryLink\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    ... on CMProductTeaser {\n      productRef {\n        product {\n          ...ProductLink\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    ... on CMExternalProduct {\n      productRef {\n        product {\n          ...ProductLink\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  callToActionEnabled\n  callToActionText\n  __typename\n}\n\nfragment CategoryLink on Category {\n  shortId\n  breadcrumb {\n    name\n    externalId\n    __typename\n  }\n  __typename\n}\n\nfragment ProductLink on Product {\n  seoSegment\n  shortId\n  category {\n    ...CategoryLink\n    __typename\n  }\n  __typename\n}\n\nfragment CMTaxonomy on CMTaxonomy {\n  ...CMLinkable\n  value\n  navigationPath {\n    segment\n    id\n    title\n    ... on CMTaxonomy {\n      value\n      __typename\n    }\n    __typename\n  }\n  __typename\n}\n\nfragment CMCollection on CMCollection {\n  ...CMTeasable\n  viewtype\n  items {\n    ...CMTeasable\n    ...CMProductTeaser\n    ...CMImageMap\n    ...CMExternalChannel\n    ...CMProduct\n    ...CMExternalLink\n    ...ProductRef\n    ...CMExternalProduct\n    ...CMDownload\n    __typename\n  }\n  __typename\n}\n\nfragment CMProductTeaser on CMProductTeaser {\n  ...CMTeasable\n  productRef {\n    ...ProductRef\n    __typename\n  }\n  shopNowSetting: settings(paths: [\"shopNow\"])\n  ctaSettings: settings(\n    paths: [\"callToActionDisabled\", \"callToActionCustomText\", \"callToActionStyle\"]\n  )\n  __typename\n}\n\nfragment ProductRef on ProductRef {\n  siteId\n  storeId\n  locale\n  externalId\n  product {\n    ...Product\n    __typename\n  }\n  __typename\n}\n\nfragment Product on Product {\n  id\n  siteId\n  name\n  shortDescription\n  offerPrice\n  listPrice\n  currency\n  locale\n  externalId\n  ...ProductLink\n  thumbnailUrl\n  augmentation {\n    id\n    picture {\n      ...CMPicture\n      __typename\n    }\n    __typename\n  }\n  __typename\n}\n\nfragment CMImageMap on CMImageMap {\n  ...CMTeasable\n  overlayConfiguration: settings(paths: [\"overlay\"])\n  transformedHotZones {\n    crops {\n      name\n      coords {\n        x\n        y\n        __typename\n      }\n      __typename\n    }\n    points {\n      x\n      y\n      __typename\n    }\n    alt\n    shape\n    target\n    displayAsInlineOverlay\n    inlineOverlayTheme\n    linkedContent {\n      ...CMTeasable\n      ...CMProductTeaser\n      ...CMExternalProduct\n      __typename\n    }\n    __typename\n  }\n  __typename\n}\n\nfragment CMExternalProduct on CMExternalProduct {\n  ...CMTeasable\n  productRef {\n    ...ProductRef\n    __typename\n  }\n  shopNowSetting: settings(paths: [\"shopNow\"])\n  __typename\n}\n\nfragment CMExternalChannel on CMExternalChannel {\n  ...CMTeasable\n  categoryRef {\n    ...CategoryRef\n    __typename\n  }\n  __typename\n}\n\nfragment CategoryRef on CategoryRef {\n  id\n  siteId\n  storeId\n  locale\n  externalId\n  category {\n    ...Category\n    __typename\n  }\n  __typename\n}\n\nfragment Category on Category {\n  id\n  siteId\n  externalId\n  name\n  ...CategoryLink\n  augmentation {\n    picture {\n      ...CMPicture\n      __typename\n    }\n    __typename\n  }\n  __typename\n}\n\nfragment CMProduct on CMProduct {\n  ...CMTeasable\n  productName\n  __typename\n}\n\nfragment CMExternalLink on CMExternalLink {\n  ...CMTeasable\n  url\n  openInNewTab\n  __typename\n}\n\nfragment CMDownload on CMDownload {\n  ...CMTeasable\n  data {\n    uri\n    __typename\n  }\n  __typename\n}\n\nfragment ShoppableVideo on CMVideo {\n  viewtype\n  timeLine {\n    defaultTarget {\n      ...CMTeasable\n      __typename\n    }\n    sequences {\n      startTimeMillis\n      link {\n        ...CMTeasable\n        ...CMProductTeaser\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  __typename\n}\n\nfragment CMSelectionRules on CMSelectionRules {\n  id\n  defaultContent {\n    ...CMTeasable\n    ...CMCollection\n    ...CMVideo\n    ...CMImageMap\n    ...CMProductTeaser\n    __typename\n  }\n  __typename\n}\n\nfragment CMHTML on CMHTML {\n  id\n  teaserTitle\n  type\n  description\n  html\n  __typename\n}\n\nfragment CMPlaceholder on CMPlaceholder {\n  ...CMLinkable\n  ...CMTeasable\n  viewtype\n  finderConfiguration: settings(paths: [\"finderConfiguration\"])\n  __typename\n}\n\nfragment CMNavigation on CMNavigation {\n  id\n  picture {\n    ...CMPicture\n    __typename\n  }\n  segment\n  ...CMTeasable\n  ...CMLinkable\n  __typename\n}\n\nfragment LocalizedVariant on CMLinkable {\n  ...CMLinkable\n  locale\n  __typename\n}\n\nfragment CMTeasableForNavigation on CMTeasable {\n  ...CMLinkable\n  teaserTitle\n  picture {\n    ...CMPicture\n    __typename\n  }\n  teaserTargets {\n    ...TeaserTarget\n    __typename\n  }\n  __typename\n}\n\nfragment CMExternalChannelForNavigation on CMExternalChannel {\n  ...CMTeasableForNavigation\n  categoryRef {\n    ...CategoryRef\n    __typename\n  }\n  __typename\n}\n\nfragment CMCollectionForNavigation on CMCollection {\n  ...CMTeasableForNavigation\n  viewtype\n  items {\n    ...CMTeasableForNavigation\n    ...CMExternalChannelForNavigation\n    ...CMProductForNavigation\n    ...CMExternalLinkForNavigation\n    ...ProductRef\n    ...CMExternalProduct\n    __typename\n  }\n  __typename\n}\n\nfragment CMProductForNavigation on CMProduct {\n  ...CMTeasableForNavigation\n  productName\n  __typename\n}\n\nfragment CMExternalLinkForNavigation on CMExternalLink {\n  ...CMTeasableForNavigation\n  url\n  openInNewTab\n  __typename\n}"}`
Response:
`{"errors":[{"message":"Cannot query field \"uuid\" on type \"CMLinkable\". Did you mean \"id\"?","locations":[{"line":204,"column":3}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED","stacktrace":["GraphQLError: Cannot query field \"uuid\" on type \"CMLinkable\". Did you mean \"id\"?","    at Object.Field (/home/olegs/projects/ocm/node_modules/.pnpm/graphql@16.7.1/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)","    at Object.enter (/home/olegs/projects/ocm/node_modules/.pnpm/graphql@16.7.1/node_modules/graphql/language/visitor.js:301:32)","    at Object.enter (/home/olegs/projects/ocm/node_modules/.pnpm/graphql@16.7.1/node_modules/graphql/utilities/TypeInfo.js:391:27)","    at visit (/home/olegs/projects/ocm/node_modules/.pnpm/graphql@16.7.1/node_modules/graphql/language/visitor.js:197:21)","    at validate (/home/olegs/projects/ocm/node_modules/.pnpm/graphql@16.7.1/node_modules/graphql/validation/validate.js:91:24)","    at processGraphQLRequest (/home/olegs/projects/ocm/node_modules/.pnpm/@apollo+server@4.9.0_graphql@16.7.1/node_modules/@apollo/server/src/requestPipeline.ts:246:38)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async internalExecuteOperation (/home/olegs/projects/ocm/node_modules/.pnpm/@apollo+server@4.9.0_graphql@16.7.1/node_modules/@apollo/server/src/ApolloServer.ts:1308:12)","    at async runHttpQuery (/home/olegs/projects/ocm/node_modules/.pnpm/@apollo+server@4.9.0_graphql@16.7.1/node_modules/@apollo/server/src/runHttpQuery.ts:232:27)","    at async runPotentiallyBatchedHttpQuery (/home/olegs/projects/ocm/node_modules/.pnpm/@apollo+server@4.9.0_graphql@16.7.1/node_modules/@apollo/server/src/httpBatching.ts:85:12)"]}}]}
`

Why can't you create one file and place one line in it to reproduce everything you were asking for???

**Comment by pitgrap** [comment]
The error message is: `Cannot query field \"uuid\" on type \"CMLinkable\".`

That means, you're using a newer version of this workspace using uuids, which your testsysten doesn't support. 

> Which CMCC version are https://headless-server-preview.cm95.coremedia.training/ based on? Did you start the same headless client version? New releases are mostly not backward-compatible.

@mbuse, can you help with the versions?

**Comment by mbuse** [comment]
The training workspace and the deployed training instances are on version CMCC-11.2110.1 (GA). At that time the React-Application did not yet exist. 

If you want to try out the React-App you should do it together with the latest version of CMCC-11.

Sorry for the inconvenience.

**Comment by mbuse** [comment]
We prepared another training instance for our CMCC-11 Content Creation Trail, which uses the Spark-App + Commerce Mock integration. This instance is based on our presales demo on version CMCC-11.2210.1.

You might try it out:
https://overview.cm56.coremedia.training/

**Comment by OlegKunitsyn** [comment]
`COREMEDIA_ENDPOINT=https://headless-server-preview.cm56.coremedia.training/graphql`

```
pnpm start

> @coremedia-labs/headless-client-workspace@2307.0.0 start /home/olegs/projects/ocm
> concurrently "pnpm --filter @coremedia-labs/headless-server-mocking start" "pnpm --filter @coremedia-labs/headless-server-stitching start" "pnpm --filter @coremedia-labs/spark start"

[1] 
[1] > @coremedia-labs/headless-server-stitching@1.0.0 start /home/olegs/projects/ocm/servers/stitching
[1] > nodemon --watch "src/**" --ext "ts" --exec "ts-node ./src/index.ts"
[1] 
[2] 
[2] > @coremedia-labs/spark@1.0.0 start /home/olegs/projects/ocm/apps/spark
[2] > vite
[2] 
[0] 
[0] > @coremedia-labs/headless-server-mocking@1.0.0 start /home/olegs/projects/ocm/servers/mocking
[0] > node ./bin/smoke -o all -d 10 mocks
[0] 
[1] [nodemon] 3.0.1
[1] [nodemon] to restart at any time, enter `rs`
[1] [nodemon] watching path(s): src/**
[1] [nodemon] watching extensions: ts
[1] [nodemon] starting `ts-node ./src/index.ts`
[0] 2023-10-06 11:09:57 [INFO]  Mocking server started on: http://localhost:5000
[2] 
[2]   VITE v4.4.7  ready in 343 ms
[2] 
[2]   ➜  Local:   http://localhost:5173/
[2]   ➜  Network: use --host to expose
[1] 2023-10-06 11:09:59 [INFO]  Fetching schemas from GraphQL endpoints
[1] 2023-10-06 11:09:59 [INFO]  Loading schema from https://headless-server-preview.cm56.coremedia.training/graphql (Headless Server).
[1] 2023-10-06 11:10:01 [INFO]  Successfully loaded schema from coreMediaHeadlessServerEndpoint.
[1] 2023-10-06 11:10:01 [INFO]  Loading schema from http://localhost:5000/graphql (Headless Commerce Server).
[1] 2023-10-06 11:10:01 [INFO]  Successfully loaded schema from commerceCatalogEndpoint.
[1] 2023-10-06 11:10:01 [INFO]  Campaign Service not configured.
[1] 2023-10-06 11:10:01 [INFO]  Stitching server started on: http://localhost:4000/graphql
```
**404 - Page not found**
POST  http://localhost:4000/graphql
`{"data":{"content":{"site":null,"pageByPath":null,"__typename":"ContentRoot"}}}`
